export const BLOG_CATEGORIES = [
  'Cybersecurity',
  'Software Development',
  'Architecture',
  'DevOps',
  'Cloud',
  'Performance',
];

export const BLOG_POSTS = [
  {
    id: '1',
    slug: 'zero-trust-architecture-modern-security',
    title: 'Zero Trust Architecture: The Future of Modern Security',
    description: 'Understanding how zero trust security models eliminate implicit trust and protect enterprise networks in the age of remote work and cloud computing.',
    excerpt: 'Explore zero trust architecture principles and how they fundamentally change how we approach network security. Learn why this model is becoming the gold standard for enterprise security.',
    image: 'https://images.pexels.com/photos/392018/pexels-photo-392018.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
    categories: ['Cybersecurity', 'Architecture'],
    tags: ['security', 'zero-trust', 'enterprise'],
    createdAt: '2026-03-10T10:00:00Z',
    cover: 'https://images.pexels.com/photos/392018/pexels-photo-392018.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
  },
  {
    id: '2',
    slug: 'react-performance-optimization-guide',
    title: 'React Performance Optimization: Beyond the Basics',
    description: 'Deep dive into advanced React optimization techniques including code splitting, lazy loading, and memoization strategies for production applications.',
    excerpt: 'Learn advanced techniques to optimize React applications. Discover how to profile performance bottlenecks and implement solutions that scale.',
    image: 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
    categories: ['Software Development', 'Performance'],
    tags: ['react', 'performance', 'optimization'],
    createdAt: '2026-03-08T14:30:00Z',
    cover: 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
  },
  {
    id: '3',
    slug: 'kubernetes-deployment-best-practices',
    title: 'Kubernetes Deployment Best Practices for Production',
    description: 'Essential patterns and practices for deploying containerized applications on Kubernetes, from resource management to security considerations.',
    excerpt: 'Master Kubernetes deployments with proven best practices. Understand resource limits, health checks, and deployment strategies that minimize downtime.',
    image: 'https://images.pexels.com/photos/207580/pexels-photo-207580.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
    categories: ['DevOps', 'Cloud'],
    tags: ['kubernetes', 'docker', 'devops'],
    createdAt: '2026-03-05T09:15:00Z',
    cover: 'https://images.pexels.com/photos/207580/pexels-photo-207580.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
  },
  {
    id: '4',
    slug: 'microservices-architecture-challenges',
    title: 'Microservices Architecture: Challenges and Solutions',
    description: 'Explore the real challenges of building microservices systems, including service discovery, distributed transactions, and monitoring strategies.',
    excerpt: 'Microservices offer scalability but introduce complexity. Learn how to handle common challenges and design resilient distributed systems.',
    image: 'https://images.pexels.com/photos/3945683/pexels-photo-3945683.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
    categories: ['Architecture', 'Software Development'],
    tags: ['microservices', 'architecture', 'distributed-systems'],
    createdAt: '2026-03-02T11:45:00Z',
    cover: 'https://images.pexels.com/photos/3945683/pexels-photo-3945683.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
  },
  {
    id: '5',
    slug: 'api-security-penetration-testing',
    title: 'API Security: Common Vulnerabilities and Testing Strategies',
    description: 'Comprehensive guide to identifying and preventing API security vulnerabilities through effective penetration testing and security hardening.',
    excerpt: 'APIs are frequently targeted attack vectors. Learn how to test APIs for vulnerabilities and implement security controls that protect user data.',
    image: 'https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
    categories: ['Cybersecurity'],
    tags: ['api-security', 'penetration-testing', 'owasp'],
    createdAt: '2026-02-28T16:20:00Z',
    cover: 'https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
  },
  {
    id: '6',
    slug: 'cloud-infrastructure-cost-optimization',
    title: 'Cloud Infrastructure Cost Optimization Without Sacrificing Performance',
    description: 'Practical strategies for reducing cloud computing costs while maintaining application performance and availability across AWS, Azure, and GCP.',
    excerpt: 'Cloud bills can spiral quickly. Discover proven strategies for optimizing resources, right-sizing instances, and monitoring costs effectively.',
    image: 'https://images.pexels.com/photos/5632399/pexels-photo-5632399.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
    categories: ['Cloud', 'DevOps'],
    tags: ['cloud', 'cost-optimization', 'aws'],
    createdAt: '2026-02-25T13:00:00Z',
    cover: 'https://images.pexels.com/photos/5632399/pexels-photo-5632399.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
  },
  {
    id: '7',
    slug: 'typescript-advanced-patterns',
    title: 'TypeScript Advanced Patterns: Generics, Utilities, and Type Guards',
    description: 'Master advanced TypeScript concepts to build more maintainable and type-safe applications with proper generic strategies and utility types.',
    excerpt: 'Take your TypeScript skills to the next level. Learn generics, conditional types, and advanced patterns used by top-tier production codebases.',
    image: 'https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
    categories: ['Software Development'],
    tags: ['typescript', 'advanced-patterns', 'type-safety'],
    createdAt: '2026-02-22T10:30:00Z',
    cover: 'https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
  },
  {
    id: '8',
    slug: 'incident-response-playbook',
    title: 'Building an Effective Incident Response Playbook',
    description: 'Create and maintain incident response procedures that minimize damage, detect threats faster, and ensure proper post-incident analysis.',
    excerpt: 'When breaches happen, quick response matters. Build playbooks that enable your team to respond rapidly and effectively to security incidents.',
    image: 'https://images.pexels.com/photos/2769274/pexels-photo-2769274.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
    categories: ['Cybersecurity'],
    tags: ['incident-response', 'security-ops', 'compliance'],
    createdAt: '2026-02-20T15:45:00Z',
    cover: 'https://images.pexels.com/photos/2769274/pexels-photo-2769274.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
  },
  {
    id: '9',
    slug: 'database-scaling-sharding-replicas',
    title: 'Database Scaling: Sharding, Replicas, and Read Optimization',
    description: 'Explore database scaling strategies including horizontal scaling, replication, and partitioning to handle growing data and traffic loads.',
    excerpt: 'Databases are often the bottleneck. Learn how to scale databases effectively using sharding, replicas, and advanced query optimization.',
    image: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
    categories: ['Architecture', 'Performance'],
    tags: ['databases', 'scaling', 'postgresql'],
    createdAt: '2026-02-18T12:00:00Z',
    cover: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=1200&h=800&dpr=2',
  },
];
